### ISSUE TITLE
Data cleaning opportunity: trait type

### ISSUE THREAD

**Issue by jar398** [EOL/eol_website#31]
Here are counts of Trait nodes by their 'type' property

        11294878  measurement
           16155  ""  (empty string)
          471415  association
           20220  metadata 
           33449  value
          226703  (null)

This seems a bit suspicious to me.  Not sure what is the semantics of null (no value for type property) and how it is different from empty string?  My guess is that both are errors.

**Comment by jar398** [comment]
oh sorry it's the 'type' property of the 'Term'  that is the trait's 'predicate'.

**Comment by jhammock** [comment]
The values playing the role of predicates will be a data cleaning opportunity for admin; I'll have a look. I'm not sure what to make of the nulls and empty strings, but the admin tool can leave term type= Unknown or blank, which seem plausible matches, which would make those an admin task too. Can I steal your query, Jonathan? I could use a scaffold to build my "give me a list of these terms" queries.

**Comment by jar398** [comment]
I think I did them as six separate queries because I haven't yet learned how to get multiple counts in a single query. Get the counts with queries similar to

     MATCH (t:Trait)-[:predicate]->(pred:Term {type: "measurement"}) RETURN COUNT(t) LIMIT 10
     MATCH (t:Trait)-[:predicate]->(pred:Term) WHERE pred.type IS NULL RETURN COUNT(t) LIMIT 10

You already have the list of types; I got it with something like this (long running):

     MATCH (t:Trait)-[:predicate]->(pred:Term) RETURN DISTINCT pred.type LIMIT 10

**Comment by jhammock** [comment]
Thanks! Most of these are now corrected in the harvesting layer and should update to the graph next sync. A few of them are value terms that we used inappropriately as predicates, which is a *different* admin data cleaning opportunity.
