### ISSUE TITLE
unable to get auth token

### ISSUE THREAD

**Issue by madhums** [EOL/eol_website#33]
I am trying to access the api's but I always get a 403 because I am not a power user. Would anyone be able to make me a power user? I emailed to the email id provided in the docs https://github.com/EOL/eol_website/blob/master/doc/api.md#authorization But have not got any response yet.

**Comment by jhammock** [comment]
Sorry, @madhums ! That should have been me. What is the url of your EOL user account?We'll hook you up.

**Comment by madhums** [comment]
Hi, this is the url of my user account https://eol.org/users/92281

**Comment by madhums** [comment]
Thanks in advance! :)

**Comment by jhammock** [comment]
OK, your privileges are active. You should be able to get to the authenticate page after logging in. Let us know if you have any more trouble!

**Comment by madhums** [comment]
Thank you!
